config/routes.rb
Rails.application.routes.draw do
  resources :works, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

  root 'top#index'

#️⃣ked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def new
    if params[:back]
      @work= Work.new(works_params)
    else
      @work = Work.new
    end
  end

  def create
    @work = Work.new(works_params)
    if @work.save
      # 一覧画面へ遷移して"ブレシピを作成しました！"とメッセージを表示します。
      redirect_to works_path, notice: "作品レシピを作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end

  def edit
   @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    @work.update(works_params)
    redirect_to works_path
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to works_path
  end

  def confirm
    @work = Work.new(works_params)
     render :new if @work.invalid?
  end

  private
    def works_params
      params.require(:work).permit(:title, :material, :production1, :production2, :production3)
    end

    def set_blog
      @work = Work.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/works_helper.rb
module WorksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_works_path
    elsif action_name == 'edit'
      work_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DiyRecital</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>DIY RECITAL</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
      <div id="header">DIY RECITAL</div>
      <img id="top-image" src="/assets/images/image.jpeg">
      <nav id="links">
        <ul>
            <li>
                <a id="works" href="https://google.co.jp">Works</a>
            </li>
            <li>
                <a id="news" href="https://yahoo.co.jp">Diy News</a>
            </li>
        </ul>
      </nav>
    </body>
</html>

app/views/works/_form.html.erb
<%= form_for(@work, url: choose_new_or_edit) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      # バリデーションエラーの件数を表示します。
      <h2><%= @work.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :material %>
  <%= f.text_field :material %>
  <br>
  <%= f.label :production1 %>
  <%= f.text_field :production1 %>
  <br>
  <%= f.label :production2 %>
  <%= f.text_field :production2 %>
  <br>
  <%= f.label :production3 %>
  <%= f.text_field :production3 %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "作品一覧画面にもどる", works_path %>

app/views/works/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@work) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :title %>
  <%= f.hidden_field :material %>
  <%= f.hidden_field :production1 %>
  <%= f.hidden_field :production2 %>
  <%= f.hidden_field :production3 %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>タイトル:<%= @work.title %></p>
  <p>材料:<%= @work.material %></p>
  <p>課程1:<%= @work.production1 %></p>
  <p>課程2:<%= @work.production2 %></p>
  <p>課程3:<%= @work.production3 %></p>
  <%= f.submit "作品を公開する" %>
<% end %>

<%= form_for(@work, url: new_work_path, method: 'get') do |f| %>
<%= f.hidden_field :title %>
<%= f.hidden_field :material %>
<%= f.hidden_field :production1 %>
<%= f.hidden_field :production2 %>
<%= f.hidden_field :production3 %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

app/views/works/edit.html.erb
<%= form_for(@work) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :material %>
<%= f.text_field :material %>
<br>
<%= f.label :production1 %>
<%= f.text_field :production1 %>
<br>
<%= f.label :production2 %>
<%= f.text_field :production2 %>
<br>
<%= f.label :production3 %>
<%= f.text_field :production3 %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "作品一覧に戻る", works_path %>

app/views/works/index.html.erb
<link rel="stylesheet" href="mobirise/style.css">

<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>


    <%= fa_icon("home 5x") %>
    <h3>作品一覧</h3>
<% @works.each do |work| %>
  <div class="row">
  <h4><strong><p>タイトル:<%= work.title %><h4><strong>
  <p>材料:<%= work.material %></p>
  <p>課程1:<%= work.production1 %></p>
  <p>課程2:<%= work.production2 %></p>
  <p>課程3:<%= work.production3 %></p>


  <%= link_to "作品レシピを編集する", edit_work_path(work.id), class: 'btn btn-sm btn-success' %>
  <%= link_to "作品レシピを削除する", work_path(work.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-sm btn-danger' %>
  </div>
<% end %>

<%= link_to "作品レシピを作成する", new_work_path %>

app/views/works/new.html.erb
<h2>作品レシピを作成する</h2>

<%= render 'form' %>